<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\vboxuser\source\repos\CodeReviews.Console.MathGame\MathGame\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\vboxuser\source\repos\CodeReviews.Console.MathGame\MathGame\.editorconfig" />
  </ItemGroup>

</Project>
