@startuml
'https://plantuml.com/state-diagram

[*] --> AppStart
AppStart --> [*] : quit
AppStart -->  ExampleSolution : choose training
AppStart --> HistoryView : view history
ExampleSolution --> ExampleSolution : play again
ExampleSolution --> AppStart : back
HistoryView --> AppStart : back

@enduml