@startuml
'https://plantuml.com/activity-diagram-beta

!pragma useVerticalIf on

start

repeat

  if (screen is main menu)
    :wait for the prompt;
    if (choose training) then (yes)
      :screen = train example; 
    elseif (view history) then (yes)
      :screen = history screen;
    else 
      :quit = true;
    endif
  elseif (screen is train example)
    repeat
      :print example;
      :ask answer;
      :compare answer;
      :save turn to history;
    repeat while (try again?)
  elseif (screen is history screen) then (yes)
    :print history;
    :wait for the prompt;
  endif

repeat while (quit is not true)

stop

@enduml
