name: Project Submission

on:
  pull_request_target: 
    branches: [ "main" ]
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: 
  pull-requests: write
  issues: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-submission-workflow:
    uses: the-csharp-academy/base-repo/.github/workflows/project-submission.yml@main
